# Generated by Django 2.1.3 on 2018-12-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lease',
            fields=[
                ('leaseid', models.IntegerField(primary_key=True, serialize=False)),
                ('landlordname', models.CharField(max_length=100)),
                ('tenantname', models.CharField(max_length=100)),
                ('apartmentsname', models.CharField(blank=True, default=None, max_length=100)),
                ('housename', models.CharField(blank=True, default=None, max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('securitydeposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='renewal',
            fields=[
                ('renewalid', models.IntegerField(primary_key=True, serialize=False)),
                ('renewaldate', models.DateField()),
                ('renewalperiod', models.CharField(max_length=100)),
            ],
        ),
    ]
