# Generated by Django 2.1.3 on 2018-12-07 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal',
            name='leaseid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaseid+', to='leasess.lease'),
        ),
    ]
