# Generated by Django 2.1.3 on 2018-12-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leasess', '0002_renewal_leaseid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='lease',
            new_name='leasess',
        ),
        migrations.RenameField(
            model_name='leasess',
            old_name='leaseid',
            new_name='leasessid',
        ),
        migrations.RemoveField(
            model_name='renewal',
            name='leaseid',
        ),
        migrations.AddField(
            model_name='renewal',
            name='leasessid',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leasessid+', to='leasess.leasess'),
        ),
    ]
